import './globals.css'
import type { Metadata } from 'next'
import { Inter, Bebas_Neue } from 'next/font/google'

const inter = Inter({ variable: '--font-inter', subsets: ['latin'] })
const bebas = Bebas_Neue({ variable: '--font-bebas-neue', subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${bebas.variable} ${inter.variable} font-sans`} lang="en">
      <body>{children}</body>
    </html>
  )
}
